# Copyright (c) 2021-2024 D-Robotics Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model_parameters:
  onnx_model: './efficientformerv2_s2_deploy.onnx'
  march: "bayes-e"
  layer_out_dump: False
  working_dir: 'EfficientFormerv2_s2-deploy_224x224_nv12'
  output_model_file_prefix: 'EfficientFormerv2_s2-deploy_224x224_nv12'

  node_info: {
    "/stages/stages.2/blocks/blocks.8/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.2/blocks/blocks.9/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.2/blocks/blocks.10/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.2/blocks/blocks.11/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/downsample/attn/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/blocks/blocks.4/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/blocks/blocks.5/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/blocks/blocks.7/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/blocks/blocks.4/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/stages/stages.3/blocks/blocks.6/token_mixer/Softmax": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    }
  }

input_parameters:
  input_name: ""
  input_type_rt: 'nv12'
  input_type_train: 'rgb'
  input_layout_train: 'NCHW'
  input_shape: ''
  norm_type: 'data_mean_and_scale'
  mean_value: 123.675 116.28 103.53
  scale_value: 0.01712475 0.017507 0.01742919

calibration_parameters:
  cal_data_dir: './calibration_data_rgb_f32'
  cal_data_type: 'float32'
  calibration_type: 'max'
  max_percentile: 0.9995

compiler_parameters:
  compile_mode: 'latency'
  debug: False
  optimize_level: 'O3'
  
