model_parameters:
  onnx_model: './yolov8n.onnx'
  march: "bayes-e"  # X3: Bernoulli2, Ultra: Bayes, S100: Nash-e, S100P: Nash-m
  layer_out_dump: False
  working_dir: 'yolov8n_detect_bayese_640x640_nv12'
  output_model_file_prefix: 'yolov8n_detect_bayese_640x640_nv12'
input_parameters:
  input_name: ""
  input_type_rt: 'nv12'
  input_type_train: 'rgb'
  input_layout_train: 'NCHW'
  norm_type: 'data_scale'
  scale_value: 0.003921568627451
calibration_parameters:
  cal_data_dir: './calibration_data_rgb_f32_640'
  cal_data_type: 'float32'
compiler_parameters:
  compile_mode: 'latency'
  debug: False
  optimize_level: 'O3'